### ISSUE TITLE
Contract.originated issue in 1.4

### ISSUE THREAD

**Issue by glottologist** [marigold-dev/breathalyzer#14]
![image](https://github.com/marigold-dev/breathalyzer/assets/57174310/bebe5f4c-0d31-448a-9261-45e9b7639b5a)

**Comment by aguillon** [comment]
As discussed on Slack, this seems to appear with slightly outdated versions Ligo. Breathalyzer being a cutting-edge library for the cool kids, I decide to close this issue.
